"use client";

import { useState } from "react";
import { createLearnerSnapshot, type LearnerSnapshot } from "@/lib/learner-snapshot";

type Props = { onComplete: (snapshot: LearnerSnapshot) => void };
const steps = ["Контекст", "Цель", "Формат", "Проверка"];

export function LearnerOnboarding({ onComplete }: Props) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ role: "", domain: "", primaryGoal: "Развиваться в профессии", goalHorizon: "quick" as const, language: "ru" as const, dailyTime: "20" as const, preferredFormat: "mixed" as const, explanationComplexity: "simple" as const, interests: "" });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const complete = () => onComplete(createLearnerSnapshot({ ...form, ...(form.role ? { role: form.role } : {}), ...(form.domain ? { domain: form.domain } : {}), ...(form.interests ? { interests: form.interests } : {}), enabledPersonalizationSignals: ["role", "domain", "primaryGoal", "dailyTime", "preferredFormat", "interests"] }));
  return <section className="mx-auto flex min-h-[100svh] max-w-xl flex-col justify-center px-5 py-12 text-[var(--text)]"><p className="text-sm text-[var(--accent-key)]">Шаг {step + 1} из {steps.length} · {steps[step]}</p><div className="mt-3 h-1 rounded bg-[var(--panel-border)]"><div className="h-full rounded bg-[var(--accent)]" style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div>{step === 0 ? <><h1 className="mt-8 text-4xl font-semibold">Расскажите о своём контексте</h1><input value={form.role} onChange={(e) => update("role", e.target.value)} placeholder="Ваша роль или профессия" className="mt-6 w-full rounded-xl p-4 text-black" /><input value={form.domain} onChange={(e) => update("domain", e.target.value)} placeholder="Сфера деятельности (необязательно)" className="mt-3 w-full rounded-xl p-4 text-black" /></> : step === 1 ? <><h1 className="mt-8 text-4xl font-semibold">К чему вы движетесь?</h1><input value={form.primaryGoal} onChange={(e) => update("primaryGoal", e.target.value)} className="mt-6 w-full rounded-xl p-4 text-black" /></> : step === 2 ? <><h1 className="mt-8 text-4xl font-semibold">Как вам удобнее учиться?</h1><select value={form.dailyTime} onChange={(e) => update("dailyTime", e.target.value)} className="mt-6 w-full rounded-xl p-4 text-black"><option value="10">10 минут в день</option><option value="20">20 минут в день</option><option value="40">40 минут в день</option></select><input value={form.interests} onChange={(e) => update("interests", e.target.value)} placeholder="Интересы для примеров (необязательно)" className="mt-3 w-full rounded-xl p-4 text-black" /></> : <><h1 className="mt-8 text-4xl font-semibold">Ваш контекст обучения</h1><p className="mt-4 text-[var(--text-2)]">Мы используем только выбранный контекст для примеров, практики и темпа. Это не оценка ваших способностей.</p><dl className="mt-6 space-y-2"><div><dt>Роль</dt><dd>{form.role || "Не указана"}</dd></div><div><dt>Цель</dt><dd>{form.primaryGoal}</dd></div><div><dt>Время</dt><dd>{form.dailyTime} минут в день</dd></div></dl></>}<div className="mt-8 flex justify-between"><button onClick={() => setStep((value) => Math.max(0, value - 1))} disabled={!step}>Назад</button><button onClick={() => step === steps.length - 1 ? complete() : setStep((value) => value + 1)}>{step === steps.length - 1 ? "Сохранить профиль" : "Далее"}</button></div></section>;
}
